(package-initialize)

(let ((default-directory "~/.emacs.d/"))
  (normal-top-level-add-subdirs-to-load-path))

(setq use-package-always-ensure t)
(setq-default indent-tabs-mode nil)

(setq ring-bell-function 'ignore)
(setq mac-option-key-is-meta nil)
(setq mac-command-key-is-meta t)
(setq mac-command-modifier 'meta)
(setq mac-option-modifier nil)

(toggle-frame-maximized)

(require 'smex)
(require 'eclim)
(require 'ido)
(require 'simp)
(require 'auto-complete)
(require 'dired)
(require 'dired-efap)
(require 'smart-indent-rigidly)
(require 'my-isearch)
(require 'my-advice)
(require 'my-backup)
(require 'my-package)
(require 'my-autoloads)
(require 'magit)
(require 'sclang)
(require 'my-functions)
(require 'my-keybindings)
(require 'my-hooks)
(require 'my-settings)
(require 'my-initializers)
(require 'my-project-definitions)
(require 'my-add-to-lists)
(require 'fill-column-indicator)

(require 'web-mode)
(require 'elixir-mode)
(require 'yaml-mode)
(require 'move-dup)
(require 'sclang)
(require 'w3m)

(server-start)
